### PR TITLE
Created the QuestionScoreDetails component

### LINKED ISSUE #97: Component: QuestionScoreDetails
Used in the ModalScoresByQuestion component. Mostly a wrapper component.

image

### PR DESCRIPTION
**Pull request by maufcost**
Fixes #97

### CODE REVIEW

**Comment by maufcost** [comment]
There are three types of questions wherein I need to look out for in order to pass the appropriate `response` prop to the `QuestionPreview` component (MC, QA, and Media).
Currently, if `QuestionScoreDetails` presents an MC question, I will send the answer ID of the correct answer to `QuestionPreview`.

For now, QA and Media questions do not have any mock-up data, so I'm not sending anything to `QuestionPreview` when these types of questions are sent to `QuestionScoreDetails`. 

If a QA or Media question is sent to `QuestionScoreDetails`, will their correct answer be under the `answerID` prop as well?

**Review by zachberry — CHANGES_REQUESTED** [review]
I added storybook test cases for QA and Media questions and merged in the latest dev/3.

* For now, the MC questions create a graph hardcoded to show 'A' through 'D'. This needs to be dependent on the choices inside the question. For multiple choice questions, that would be the size of props.question.answers (in the example, there's two, so there would only be 'A' and 'B'). For QA (short answer) questions I'm thinking we simply have two bars - "Incorrect" and "Correct". For media questions, we could have a bar for "< 100" and "100" (It'd be better to break that down further, but I'm not sure we have the space).
* The DefList component probably has to change for Media questions. With a media question I think instead of 'Std Dev' we change that to 'Mean' and compute the average.

**Comment by maufcost** [comment]
I made all the changes in the above comment :) There are a few conundrums that I came across though:

- I don't think it is possible to get the standard deviation on only two data types (like in the QA question type with its Correct and Incorrect attributes). Because of that, I changed its def list parameter from getting **standard deviation** to **accuracy**. Let me know if you need me to change that!

- When it comes to sending a response to the question preview component, how would you prefer to get it done? Currently, for MC questions: I send the correct answer letter to the response (e.g.: A, B, C, etc). For both QA and MEDIA questions, I am only sending the last question answered by the given student (perhaps if we could click on a data grid row of specific response, we could change what is sent to the question preview component).

**Review by zachberry — CHANGES_REQUESTED** [review]
Awesome! For the student response, we can just omit it - that's optional. Accuracy makes sense to me. As far as mean, I think the calculation is incorrect - in the media question example I see a mean of 1 but I think it should be 0.5. Finally, I'm thinking we report accuracy and mean as percentages (50% instead of 0.5).

**Comment by maufcost** [comment]
Nice! I omitted the response props for the question preview component for `QA` and `MEDIA` questions. Let me know if you need me to make any more changes!

**Review by zachberry — APPROVED** [review]
Changes all look good, the only thing I saw is that it was still sending `response` into `QuestionPreview`, so I removed that and seems to be working!

**Pull request merged**
