### PR TITLE
Added the DataGridQuestionNumberCell component

### LINKED ISSUE #104: Component: DataGridQuestionNumberCell
Used in the DataGridStudentScores component. Lists the question number (as well as if it's a question alternate, where available)

image

### PR DESCRIPTION
**Pull request by maufcost**
**Note:**  
- The cell is currently extending to the full width of the screen because it's a `block` element. When it is plugged into its parent data grid, it will resize it appropriately within its container.
- Based on the screenshot, I assumed that the maximum number of alternate questions is 2 (also because in the props, if there is an alternate question, the only props currently being passed to this component is the number of that question and not the number of alternate questions for that question number. Let me know if that needs to be changed!

Fixes #104

### CODE REVIEW

**Review by zachberry — CHANGES_REQUESTED** [review]
Good call. There can be more than two alternates (although usually it is only 2) - I forgot to add that as a prop. I'm thinking we add in `totalAlts`.

**Comment by zachberry** [comment]
Thinking this over more, I'm thinking we no longer allow `altNumber` to be null. Instead it's always a number. The new `totalAlts` will specify how many versions of a question there are. If `totalAlts` is 1 then we render the simple layout, i.e. "Question 8". If `totalAlts` is > 1 then we render the stacked layout, i.e.

```
Question 8
Alternate 1/3
```

**Comment by maufcost** [comment]
That makes sense now. I am making the changes, and I will post them here soon.

**Review by zachberry — APPROVED** [review]
The story file needed the new totalAlts property which I added real quick, now gtg!

**Pull request merged**
